### ISSUE TITLE
Project not running as expected

### ISSUE THREAD

**Issue by kamal-hossain** [faceplugin/Face-Recognition-SDK-Demo-React#1]
Hello there, thanks for this beautiful project. I have cloned the repository and done the instruction from the Readme. 
But the project is not running as expected.

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/47250512/236117998-243bb80b-d0b8-4467-bf9b-a8feb2da377d.png">

## Can you help me to run this project?

**Comment by faceplugin** [comment]
Hello @kamal-hossain 
I will fix this issue asap.

**Comment by faceplugin** [comment]
Hello @kamal-hossain 
Please check the latest.
Sorry for delay
